packages:
  - packages/*
  - workers/*

overrides:
  esbuild: 0.25.1
catalogs:
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@hiogawa/node-loader-cloudflare': 0.0.2
    '@unocss/preset-mini': ^66.5.6
    '@unocss/preset-uno': ^66.5.6
    '@vitejs/plugin-react': 5.1.0
    babel-plugin-react-compiler: 1.0.0
    eslint: ^9.39.1
    jiti: ^2.6.1
    lint-staged: ^16.2.6
    miniflare: 4.20251105.0
    simple-git-hooks: ^2.13.1
    turbo: ^2.6.1
    typescript: ^5.9.3
    unocss: ^66.5.6
    vite: 7.2.2
    wrangler: ^4.47.0
  lib:
    react: 19.2.0
    react-dom: 19.2.0
    react-server-dom-webpack: 19.2.0
    waku: 0.27.0
    zod: ^4.1.12
  server:
    hono: ^4.10.5
    hono-openapi: 1.1.1
  types:
    '@types/node': 24.10.0
    '@types/react': 19.2.2
    '@types/react-dom': 19.2.2

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
