allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: false
  vue-demi: false
  workerd: true

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
  - '@resvg/resvg-js'

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - chokidar@4.0.3
  - '@unocss/webpack@66.5.10'

overrides:
  '@nuxt/content>nuxt-component-meta': 0.17.2

packageExtensions:
  h3@2.0.1-rc.32:
    optionalDependencies:
      crossws: ^0.4.12

minimumReleaseAgeExclude:
  - '@nuxt/kit-nightly@5.0.0-29846154.7802b2c2'
  - '@nuxt/nitro-server-nightly@5.0.0-29846154.7802b2c2'
  - '@nuxt/schema-nightly@5.0.0-29846154.7802b2c2'
  - '@nuxt/vite-builder-nightly@5.0.0-29846154.7802b2c2'
  - '@nuxt/vite-server-nightly@5.0.0-29846154.7802b2c2'
  - nuxt-nightly@5.0.0-29846154.7802b2c2

patchedDependencies:
  nitro@3.0.260903-beta: patches/nitro@3.0.260903-beta.patch
