/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.example --include-runtime=false shared/types/worker-configuration.d.ts` (hash: 32bba670581af5aaa8f4f04f91cbba08)
interface __BaseEnv_Env {
	BLOB: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	STUDIO_GITHUB_CLIENT_ID: string;
	STUDIO_GITHUB_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../../.output/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "STUDIO_GITHUB_CLIENT_ID" | "STUDIO_GITHUB_CLIENT_SECRET">> {}
}
