/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthLoginForm: typeof import('./components/auth/login-form.vue')['default']
    AuthManageAccountIcon: typeof import('./components/auth/manage/account/icon.vue')['default']
    AuthManageAccountInfo: typeof import('./components/auth/manage/account/info.vue')['default']
    AuthManageAccountSkeleton: typeof import('./components/auth/manage/account/skeleton.vue')['default']
    AuthManageEmailInfo: typeof import('./components/auth/manage/email/info.vue')['default']
    AuthManageModal: typeof import('./components/auth/manage/modal.vue')['default']
    AuthManagePasskeyAddPasskey: typeof import('./components/auth/manage/passkey/add-passkey.vue')['default']
    AuthManagePasskeyInfo: typeof import('./components/auth/manage/passkey/info.vue')['default']
    AuthManagePasskeySkeleton: typeof import('./components/auth/manage/passkey/skeleton.vue')['default']
    AuthManageSection: typeof import('./components/auth/manage/section.vue')['default']
    AuthManageSecurityInfo: typeof import('./components/auth/manage/security-info.vue')['default']
    AuthManageSessionIconLaptop: typeof import('./components/auth/manage/session/icon-laptop.vue')['default']
    AuthManageSessionIconMobile: typeof import('./components/auth/manage/session/icon-mobile.vue')['default']
    AuthManageSessionInfo: typeof import('./components/auth/manage/session/info.vue')['default']
    AuthManageSessionSkeleton: typeof import('./components/auth/manage/session/skeleton.vue')['default']
    AuthManageUserInfo: typeof import('./components/auth/manage/user-info.vue')['default']
    AuthModal: typeof import('./components/auth/modal.vue')['default']
    AuthSigninForm: typeof import('./components/auth/signin-form.vue')['default']
    AuthSignupForm: typeof import('./components/auth/signup-form.vue')['default']
    HomeIntro: typeof import('./components/home/intro.vue')['default']
    HomeIntroAvatar: typeof import('./components/home/intro-avatar.vue')['default']
    IconsBilibili: typeof import('./components/icons/bilibili.vue')['default']
    LayoutAuthButton: typeof import('./components/layout/auth-button.vue')['default']
    LayoutFab: typeof import('./components/layout/fab.vue')['default']
    LayoutFooter: typeof import('./components/layout/footer.vue')['default']
    LayoutNavBar: typeof import('./components/layout/nav-bar.vue')['default']
    LayoutNavBarLink: typeof import('./components/layout/nav-bar-link.vue')['default']
    LayoutNavBarMenu: typeof import('./components/layout/nav-bar-menu.vue')['default']
    LayoutThemeButton: typeof import('./components/layout/theme-button.vue')['default']
    LayoutToTopButton: typeof import('./components/layout/to-top-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiFormField: typeof import('./components/ui/form/field.vue')['default']
    UiToastToaster: typeof import('./components/ui/toast/toaster.vue')['default']
    UiTooltip: typeof import('./components/ui/tooltip.vue')['default']
    UiTooltipRoot: typeof import('./components/ui/tooltip/root.vue')['default']
    UiTooltipTrigger: typeof import('./components/ui/tooltip/trigger.vue')['default']
  }
}

// For TSX support
declare global {
  const AuthLoginForm: typeof import('./components/auth/login-form.vue')['default']
  const AuthManageAccountIcon: typeof import('./components/auth/manage/account/icon.vue')['default']
  const AuthManageAccountInfo: typeof import('./components/auth/manage/account/info.vue')['default']
  const AuthManageAccountSkeleton: typeof import('./components/auth/manage/account/skeleton.vue')['default']
  const AuthManageEmailInfo: typeof import('./components/auth/manage/email/info.vue')['default']
  const AuthManageModal: typeof import('./components/auth/manage/modal.vue')['default']
  const AuthManagePasskeyAddPasskey: typeof import('./components/auth/manage/passkey/add-passkey.vue')['default']
  const AuthManagePasskeyInfo: typeof import('./components/auth/manage/passkey/info.vue')['default']
  const AuthManagePasskeySkeleton: typeof import('./components/auth/manage/passkey/skeleton.vue')['default']
  const AuthManageSection: typeof import('./components/auth/manage/section.vue')['default']
  const AuthManageSecurityInfo: typeof import('./components/auth/manage/security-info.vue')['default']
  const AuthManageSessionIconLaptop: typeof import('./components/auth/manage/session/icon-laptop.vue')['default']
  const AuthManageSessionIconMobile: typeof import('./components/auth/manage/session/icon-mobile.vue')['default']
  const AuthManageSessionInfo: typeof import('./components/auth/manage/session/info.vue')['default']
  const AuthManageSessionSkeleton: typeof import('./components/auth/manage/session/skeleton.vue')['default']
  const AuthManageUserInfo: typeof import('./components/auth/manage/user-info.vue')['default']
  const AuthModal: typeof import('./components/auth/modal.vue')['default']
  const AuthSigninForm: typeof import('./components/auth/signin-form.vue')['default']
  const AuthSignupForm: typeof import('./components/auth/signup-form.vue')['default']
  const HomeIntro: typeof import('./components/home/intro.vue')['default']
  const HomeIntroAvatar: typeof import('./components/home/intro-avatar.vue')['default']
  const IconsBilibili: typeof import('./components/icons/bilibili.vue')['default']
  const LayoutAuthButton: typeof import('./components/layout/auth-button.vue')['default']
  const LayoutFab: typeof import('./components/layout/fab.vue')['default']
  const LayoutFooter: typeof import('./components/layout/footer.vue')['default']
  const LayoutNavBar: typeof import('./components/layout/nav-bar.vue')['default']
  const LayoutNavBarLink: typeof import('./components/layout/nav-bar-link.vue')['default']
  const LayoutNavBarMenu: typeof import('./components/layout/nav-bar-menu.vue')['default']
  const LayoutThemeButton: typeof import('./components/layout/theme-button.vue')['default']
  const LayoutToTopButton: typeof import('./components/layout/to-top-button.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UiFormField: typeof import('./components/ui/form/field.vue')['default']
  const UiToastToaster: typeof import('./components/ui/toast/toaster.vue')['default']
  const UiTooltip: typeof import('./components/ui/tooltip.vue')['default']
  const UiTooltipRoot: typeof import('./components/ui/tooltip/root.vue')['default']
  const UiTooltipTrigger: typeof import('./components/ui/tooltip/trigger.vue')['default']
}