/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthAuthModal: typeof import('./components/auth/auth-modal.vue')['default']
    AuthLoginForm: typeof import('./components/auth/login-form.vue')['default']
    AuthModal: typeof import('./components/auth/modal.vue')['default']
    AuthSignupForm: typeof import('./components/auth/signup-form.vue')['default']
    HomeIntro: typeof import('./components/home/intro.vue')['default']
    HomeIntroAvatar: typeof import('./components/home/intro-avatar.vue')['default']
    IconsBilibili: typeof import('./components/icons/bilibili.vue')['default']
    LayoutAuthButton: typeof import('./components/layout/auth-button.vue')['default']
    LayoutAuthModal: typeof import('./components/layout/auth-modal.vue')['default']
    LayoutFab: typeof import('./components/layout/fab.vue')['default']
    LayoutFooter: typeof import('./components/layout/footer.vue')['default']
    LayoutNavBar: typeof import('./components/layout/nav-bar.vue')['default']
    LayoutNavBarLink: typeof import('./components/layout/nav-bar-link.vue')['default']
    LayoutNavBarMenu: typeof import('./components/layout/nav-bar-menu.vue')['default']
    LayoutThemeButton: typeof import('./components/layout/theme-button.vue')['default']
    LayoutToTopButton: typeof import('./components/layout/to-top-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AuthAuthModal: typeof import('./components/auth/auth-modal.vue')['default']
  const AuthLoginForm: typeof import('./components/auth/login-form.vue')['default']
  const AuthModal: typeof import('./components/auth/modal.vue')['default']
  const AuthSignupForm: typeof import('./components/auth/signup-form.vue')['default']
  const HomeIntro: typeof import('./components/home/intro.vue')['default']
  const HomeIntroAvatar: typeof import('./components/home/intro-avatar.vue')['default']
  const IconsBilibili: typeof import('./components/icons/bilibili.vue')['default']
  const LayoutAuthButton: typeof import('./components/layout/auth-button.vue')['default']
  const LayoutAuthModal: typeof import('./components/layout/auth-modal.vue')['default']
  const LayoutFab: typeof import('./components/layout/fab.vue')['default']
  const LayoutFooter: typeof import('./components/layout/footer.vue')['default']
  const LayoutNavBar: typeof import('./components/layout/nav-bar.vue')['default']
  const LayoutNavBarLink: typeof import('./components/layout/nav-bar-link.vue')['default']
  const LayoutNavBarMenu: typeof import('./components/layout/nav-bar-menu.vue')['default']
  const LayoutThemeButton: typeof import('./components/layout/theme-button.vue')['default']
  const LayoutToTopButton: typeof import('./components/layout/to-top-button.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}