/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(home)': RouteRecordInfo<
      '/(home)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(home)/'
      | '/(home)/[...404]'
      | '/(home)/about'
      | '/(home)/blog/'
      | '/(home)/blog/[slug]'
      | '/(home)/guestbook'
      | '/(home)/projects'
    >,
    '/(home)/': RouteRecordInfo<
      '/(home)/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/[...404]': RouteRecordInfo<
      '/(home)/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/(home)/about': RouteRecordInfo<
      '/(home)/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/blog/': RouteRecordInfo<
      '/(home)/blog/',
      '/blog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/blog/[slug]': RouteRecordInfo<
      '/(home)/blog/[slug]',
      '/blog/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/(home)/guestbook': RouteRecordInfo<
      '/(home)/guestbook',
      '/guestbook',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(home)/projects': RouteRecordInfo<
      '/(home)/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/(dashboard)'
      | '/admin/(dashboard)/'
      | '/admin/(dashboard)/posts/'
      | '/admin/(dashboard)/posts/[id]'
      | '/admin/(dashboard)/posts/new'
      | '/admin/sign-in'
    >,
    '/admin/(dashboard)': RouteRecordInfo<
      '/admin/(dashboard)',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | '/admin/(dashboard)/'
      | '/admin/(dashboard)/posts/'
      | '/admin/(dashboard)/posts/[id]'
      | '/admin/(dashboard)/posts/new'
    >,
    '/admin/(dashboard)/': RouteRecordInfo<
      '/admin/(dashboard)/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/(dashboard)/posts/': RouteRecordInfo<
      '/admin/(dashboard)/posts/',
      '/admin/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/(dashboard)/posts/[id]': RouteRecordInfo<
      '/admin/(dashboard)/posts/[id]',
      '/admin/posts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/(dashboard)/posts/new': RouteRecordInfo<
      '/admin/(dashboard)/posts/new',
      '/admin/posts/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/sign-in': RouteRecordInfo<
      '/admin/sign-in',
      '/admin/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(home).vue': {
      routes:
        | '/(home)'
        | '/(home)/'
        | '/(home)/[...404]'
        | '/(home)/about'
        | '/(home)/blog/'
        | '/(home)/blog/[slug]'
        | '/(home)/guestbook'
        | '/(home)/projects'
      views:
        | 'banner'
        | 'default'
    }
    'src/pages/(home)/index.vue': {
      routes:
        | '/(home)/'
      views:
        | never
    }
    'src/pages/(home)/[...404].vue': {
      routes:
        | '/(home)/[...404]'
      views:
        | never
    }
    'src/pages/(home)/about.md': {
      routes:
        | '/(home)/about'
      views:
        | never
    }
    'src/pages/(home)/blog/index.vue': {
      routes:
        | '/(home)/blog/'
      views:
        | never
    }
    'src/pages/(home)/blog/index@banner.vue': {
      routes:
        | '/(home)/blog/'
      views:
        | never
    }
    'src/pages/(home)/blog/[slug].vue': {
      routes:
        | '/(home)/blog/[slug]'
      views:
        | never
    }
    'src/pages/(home)/guestbook.vue': {
      routes:
        | '/(home)/guestbook'
      views:
        | never
    }
    'src/pages/(home)/guestbook@banner.vue': {
      routes:
        | '/(home)/guestbook'
      views:
        | never
    }
    'src/pages/(home)/projects.md': {
      routes:
        | '/(home)/projects'
      views:
        | never
    }
    'src/pages/(home)/projects@banner.vue': {
      routes:
        | '/(home)/projects'
      views:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
        | '/admin/(dashboard)'
        | '/admin/(dashboard)/'
        | '/admin/(dashboard)/posts/'
        | '/admin/(dashboard)/posts/[id]'
        | '/admin/(dashboard)/posts/new'
        | '/admin/sign-in'
      views:
        | 'default'
    }
    'src/pages/admin/(dashboard).vue': {
      routes:
        | '/admin/(dashboard)'
        | '/admin/(dashboard)/'
        | '/admin/(dashboard)/posts/'
        | '/admin/(dashboard)/posts/[id]'
        | '/admin/(dashboard)/posts/new'
      views:
        | 'default'
    }
    'src/pages/admin/(dashboard)/index.vue': {
      routes:
        | '/admin/(dashboard)/'
      views:
        | never
    }
    'src/pages/admin/(dashboard)/posts/index.vue': {
      routes:
        | '/admin/(dashboard)/posts/'
      views:
        | never
    }
    'src/pages/admin/(dashboard)/posts/[id].vue': {
      routes:
        | '/admin/(dashboard)/posts/[id]'
      views:
        | never
    }
    'src/pages/admin/(dashboard)/posts/new.vue': {
      routes:
        | '/admin/(dashboard)/posts/new'
      views:
        | never
    }
    'src/pages/admin/sign-in.vue': {
      routes:
        | '/admin/sign-in'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
